name: Upload to S3

on:
  push:
    branches:
      - main  # Or any other branch you want this workflow to run on

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Specify your desired AWS region

    - name: Copy specific files to S3
      run: aws s3 sync . s3://static-demo-website --delete --exclude ".git/"